# Generated by Django 2.2 on 2019-12-05 10:14

import NewsFeed.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Themes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=32, verbose_name='Тематика')),
            ],
            options={
                'verbose_name': 'Тематика',
                'verbose_name_plural': 'Тематики',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(error_messages={'min_length': 'Слишком короткое название'}, help_text='Введите название новости', max_length=64, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Заголовок новости')),
                ('description', models.TextField(verbose_name='Содержание новости')),
                ('edit_date_time', models.DateTimeField(auto_now=True, verbose_name='Дата и время последней правки')),
                ('image', models.ImageField(blank=True, null=True, upload_to=NewsFeed.models.get_timestamp_path, verbose_name='Изображение')),
                ('creator', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('subjects', models.ManyToManyField(help_text='Подберите тематики', to='NewsFeed.Themes', verbose_name='Тематики')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-edit_date_time'],
            },
        ),
    ]
