# Generated by Django 2.2.7 on 2019-11-20 21:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Themes',
            fields=[
                ('name', models.CharField(db_index=True, max_length=32, primary_key=True, serialize=False, verbose_name='Тематика')),
            ],
            options={
                'verbose_name': 'Тематика',
                'verbose_name_plural': 'Тематики',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(error_messages={'min_length': 'Слишком короткое название'}, help_text='Введите название новости', max_length=32, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Заголовок новости')),
                ('description', models.TextField(verbose_name='Содержание новости')),
                ('edit_date_time', models.DateTimeField(auto_now=True, verbose_name='Дата и время последней правки')),
                ('subjects', models.ManyToManyField(help_text='Подберите тематики', to='NewsFeed.Themes', verbose_name='Тематики')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-edit_date_time'],
            },
        ),
    ]
