# Generated by Django 2.2 on 2019-12-03 20:21

import NewsFeed.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('NewsFeed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, upload_to=NewsFeed.models.get_timestamp_path, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='news',
            name='headline',
            field=models.CharField(error_messages={'min_length': 'Слишком короткое название'}, help_text='Введите название новости', max_length=64, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Заголовок новости'),
        ),
    ]
