# Generated by Django 2.2 on 2019-12-05 10:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsFeed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='headline',
            field=models.CharField(error_messages={'min_length': 'Слишком короткое название'}, help_text='Введите название новости', max_length=128, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Заголовок новости'),
        ),
    ]
