# Generated by Django 2.2 on 2019-12-03 20:23

import NewsFeed.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NewsFeed', '0002_auto_20191203_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=NewsFeed.models.get_timestamp_path, verbose_name='Изображение'),
        ),
    ]
